[#73] Bug 해결
riyenas0925/Sejong_Track_Management pull request #101
Opened 2019-11-27 15:37 UTC by kimhanui

- Member와 MemberRole 엔티티 연관관계 삭제

- data.sql에 위 엔티티들에 utf-8 권한 줌

Resolves #73

2019-11-27 17:11 UTC, kimhanui commented
#94  bug 해결한거고  
#73 으로 pr올리고 작업현황 알려달라해서 제목 이슈번호 [#73]으로 해놓음

2019-11-29 13:59 UTC, riyenas0925 commented
@kimhanui 굿굿 잘 구현 하고 있네 이거는 머지 할꺼?? 아님 전부다 완성 하고 머지 할까?

2019-11-29 14:01 UTC, riyenas0925 requested changes

2019-11-29 14:01 UTC, riyenas0925 commented on src/main/resources/data.sql
> +SET foreign_key_checks =1;
@kimhanui 이부분 코드가 중복되어있는것 같은데 확인 부탁

2019-11-29 14:05 UTC, riyenas0925 requested changes

2019-11-29 14:05 UTC, riyenas0925 commented on pom.xml
> +    </dependency>
@kimhanui thymeleaf 사용은 고려해봐야할것 같음.....

2019-11-29 14:05 UTC, riyenas0925 commented on src/main/java/kr/ac/sejong/controller/MemberController.java
> +//}
@kimhanui 아래에있는 _security 붙은 컨트롤러와 어떤 차이가 있는거야?

2019-11-29 14:05 UTC, kimhanui commented on src/main/resources/data.sql
> +SET foreign_key_checks =1;
아아 ㅇㅇㅇ맞어 그거 중복된건데 다음 커밋에서 수정해놓을게

2019-11-29 14:06 UTC, kimhanui commented on pom.xml
> +    </dependency>
ㅇㅇ고건 지금은 삭제햇어

2019-11-29 14:09 UTC, kimhanui commented on src/main/java/kr/ac/sejong/controller/MemberController.java
> +//}
시큐리티 쓰면 컨트롤러에서 작업할게 별로 없는것 같더라고  
ex) 로그인 인증은 service layer에서 작업
그래서 시큐리티 적용한 컨트롤러라고 구분해놓은거임ㅇㅇ 
다 구현하면 기존에 있던건 삭제할 예정.

2019-11-29 14:10 UTC, kimhanui commented
> @kimhanui 굿굿 잘 구현 하고 있네 이거는 머지 할꺼?? 아님 전부다 완성 하고 머지 할까?

흠 아직 머지할 단계는 아닌것같음   
구현 더 되면 머지해달라고 할게

2019-11-29 14:35 UTC, riyenas0925 commented
> > @kimhanui 굿굿 잘 구현 하고 있네 이거는 머지 할꺼?? 아님 전부다 완성 하고 머지 할까?
> 
> 흠 아직 머지할 단계는 아닌것같음
> 구현 더 되면 머지해달라고 할게

ㅇㅋㅇㅋ 완성되면 알려주고 마지막 커밋에 계속 Rebase 하는 형식으로 히면 bug 커밋하고 기능 커밋 이렇게 2개만 남게 하는게 좋을것 같은데 어떰??

2019-11-29 14:36 UTC, kimhanui commented
> > > @kimhanui 굿굿 잘 구현 하고 있네 이거는 머지 할꺼?? 아님 전부다 완성 하고 머지 할까?
> > 
> > 
> > 흠 아직 머지할 단계는 아닌것같음
> > 구현 더 되면 머지해달라고 할게
> 
> ㅇㅋㅇㅋ 완성되면 알려주고 마지막 커밋에 계속 Rebase 하는 형식으로 히면 bug 커밋하고 기능 커밋 이렇게 2개만 남게 하는게 좋을것 같은데 어떰??

ㅇㅋㅇㅋ그렇게 할게

2019-12-01 18:50 UTC, closed without merging