[EHN,CLN] 공지사항 게시판 crud(+멤버 서비스클래스 삭제)
riyenas0925/Sejong_Track_Management pull request #141
Opened 2020-02-12 19:03 UTC by kimhanui

EHN :

- 공지사항 게시판 crud 구현

- data.sql 수정(한글허용)

- 공지 최초 생성된 시간 , 수정된 시간 기록 칼럼 있음.

- admin계정으로만 공지 등록하도록 securityConfig설정

- restController에 글 추가 url /notice/create로 수정

CLN :

- MemberService, MemberServiceInpl 안쓰는 클래스이므로 삭제.

# 부탁 
@riyenas0925 

notice.js좀 만들어주실...? js 함수 모아넣고싶은데 잘 안되네
- noticeDetals.jsp, noticeList.jsp에 쓰이는 js함수들을 notice.js에 넣고 정리하고 싶었는데 잘 안됨.
   notice.js에서 jquery를 써서 그런가?
- 지금 있는 notice.js는 noticeDetails.jsp랑 noticeList.jsp에 있는 js함수들 걍 다 모아넣은거라(완전히 일치하진 않음) 다시 만들어야될 것 같어

Resolved #136

2020-02-14 09:56 UTC, riyenas0925 requested changes
위에 내용만 수정하고 커밋 해주라 
Pr올라온거에 대해서는 리베이스 할필요 없으

2020-02-14 09:56 UTC, riyenas0925 commented on src/main/java/kr/ac/sejong/service/NoticeService.java
> +    NoticeRepository repo;
@kimhanui @Inject 어노테이션 대신에 생성자를 만들어서 하는 방식으로 주입하자

2020-02-14 09:56 UTC, riyenas0925 commented on src/main/java/kr/ac/sejong/service/NoticeService.java
> +    public NoticeResponseDto findById(Long id) {
@kimhanui 이부분도 @transaction read only로 설정해서 사용 부탁

2020-02-14 10:56 UTC, kimhanui commented on src/main/java/kr/ac/sejong/service/NoticeService.java
> +    NoticeRepository repo;
```java
NoticeRepository repo = new NoticeRepositoryIml();
```
이렇게 하자는거야? 왜 그렇게 하는거야? @riyenas0925

2020-02-14 11:13 UTC, riyenas0925 commented on src/main/java/kr/ac/sejong/service/NoticeService.java
> +    NoticeRepository repo;
@kimhanui 아 요게 아니라 private final NoticeRepository repo 이렇게 하고 위에 어노테이션에 @Requireargsconstruct 이거 붙여주면 생성자가 만들어져서 생성자로 주입할수 있게 되거든 

참고 : https://leejisoo860911.tistory.com/m/2

2020-02-14 12:51 UTC, riyenas0925 commented
@kimhanui 아그리고 코멘트 달린 내용중에 해결 된게 있으면 Resolve conversation 눌러주라

2020-02-16 09:21 UTC, riyenas0925 approved these changes

2020-02-16 09:22 UTC, merged