CLN,TST : trackRule Clean Up,Entity CRUD Test Code #79
riyenas0925/Sejong_Track_Management pull request #89
Opened 2019-11-20 14:04 UTC by riyenas0925

- [x] 연관관계 재설정
- [x] rule과 관련된 함수들 mybatis에서 jpa로 변경

2019-11-20 14:06 UTC, riyenas0925 commented
@kimhanui 기존에는 trackId, univId로 규칙을 검색하는 방식이였는데 소융대는 트랙하나당 규칙 하나여서 괜찮은데 무인기 트랙같은 경우는 트랙 하나에 학석사, 석사, 박사, 석박사 처럼 규칙이 여러개여서 학위를 선택할수 있게 변경 했음 ㅇㅇ

2019-11-20 17:48 UTC, kimhanui requested changes

2019-11-20 17:48 UTC, kimhanui commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.format_sql=true
여긴 주석처리 한건가? 이제 로그는 필요 없음?

2019-11-20 17:48 UTC, kimhanui commented on src/main/java/kr/ac/sejong/persistence/DegreeRepository.java
> +import org.springframework.data.jpa.repository.JpaRepository;
다른 repository도 JpaRepository로 바꿀 예정이야?
+ JpaRepository가 쓰기 더 편한가?

2019-11-21 09:01 UTC, riyenas0925 commented on src/main/java/kr/ac/sejong/persistence/DegreeRepository.java
> +import org.springframework.data.jpa.repository.JpaRepository;
아 CRUD말고 JPA사용한 이유는 getOne이라는 함수가 편하기도 하고 JPA쪽으로는 이게 더 편하더라고

https://m.blog.naver.com/PostView.nhn?blogId=writer0713&logNo=221587319282&proxyReferer=https%3A%2F%2Fwww.google.com%2F

2019-11-21 09:02 UTC, riyenas0925 commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.format_sql=true
아 이거느 사지방에서 로그가 길어지면 렉걸려서 잠깐 지운건데 나중에 다시 수정할께

2019-11-21 09:04 UTC, riyenas0925 commented on src/main/java/kr/ac/sejong/persistence/DegreeRepository.java
> +import org.springframework.data.jpa.repository.JpaRepository;
![스크린샷_2019-07-16_오후_7 54 42](https://user-images.githubusercontent.com/32615702/69323069-57b8c080-0c89-11ea-8429-23322fde8d47.png)

2019-11-21 09:08 UTC, kimhanui commented on src/main/java/kr/ac/sejong/persistence/DegreeRepository.java
> +import org.springframework.data.jpa.repository.JpaRepository;
ㅇㅎ확인

2019-11-21 13:08 UTC, riyenas0925 commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.format_sql=true
@kimhanui 지금 수정 했고 확인해보고 어프로브 부탁 ㅇㅇ

2019-11-21 13:15 UTC, kimhanui commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.format_sql=true
확인

2019-11-21 13:16 UTC, kimhanui approved these changes

2019-11-21 13:16 UTC, merged